### ISSUE TITLE
Implementing it with login system

### ISSUE THREAD

**Issue by calvinhill** [sceee/aspnet-identity-rethinkdb#3]
Hello

Altough its not an issue i would apreciate if you could provide any project or example on how to implement the login system like the predefined web application created in VS

Thank you

**Comment by sceee** [comment]
Hi @calvinhill 
Sorry, at the moment I do not have an example laying around. I will try if I can provide you one with the standard example.

**Comment by calvinhill** [comment]
Thanks a lot for the response i will wait for the example :)

**Comment by calvinhill** [comment]
Can you give me any prediction for the example ? Sorry for asking

**Comment by sceee** [comment]
Sorry I have few time right now and I need to setup a new environment for this. I will try to get it on as soon as possible.

Did you try the usage explanation I put on the project home page?

**Comment by calvinhill** [comment]
Yes but I couldnt get it to work, i will wait for the example, thanks a lot for the response and sorry for the extra work

**Comment by calvinhill** [comment]
Hi, sorry for bothering again but i would like to know if you have any news about this example? thank you :)

**Comment by sceee** [comment]
Hi @calvinhill ,

Sorry for the delay, I had little time...but now I created the default Asp.net MVC sample application with the identity provider using it. Please see commit ee6a53df8be2a7ac9efd57bbd71bab8523dd0b3c and b29c3774154f1687f5d56a689882dc5150bdcb69 (or just use the latest).

Start in the App_Start/ApplicationIdentityContext.cs - there is the database connection configuration.
It should create the database and the required tables on its own at the first start in debug mode.

You will then be able to create accounts.

Additionally, I created 3 custom fields to show the usage for them (if you want to store additional information for a user such as firstname, lastname or some bytes for the profile picture).

Kept really simple, basically it's just 3 files I think. You will see.
I hope this works for you!

**Comment by calvinhill** [comment]
Hi @sceee 

I will try to use your sample, thanks a lot for your effort :)

**Comment by sceee** [comment]
Hi @calvinhill, let me know if you run into any problems.
